DROP TABLE IF EXISTS users;


CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  location VARCHAR(255) NOT NULL,
  artist_type VARCHAR(255) NOT NULL,
  looking_for VARCHAR(255) NOT NULL,
  description VARCHAR(2048) NOT NULL,
);
